Check 'PARALLEL CUSOR' with 'FETCH'/'MOVE' statement
- Added test cases to check
- Implemented: Report error on the 'MOVE' statement of parallel cursor
- Refined the error message if the cursor is already closed.

Error message changed from:

```
isolation2gp2gp=# close c1;
CLOSE CURSOR
isolation2gp2gp=# execute parallel cursor c1;
ERROR:  Cannot specify 'EXECUTE PARALLEL CURSOR' for non-parallel cursor.
HINT:  Using 'FETCH' statement instead.
```
to:
```
isolation2gp2gp=# close c1;
CLOSE CURSOR
isolation2gp2gp=# execute parallel cursor c1;
ERROR:  cursor "c1" does not exist
```